config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :books, only: %i[index show] do
    resources :reviews, only: :create
  end
  resources :carts, only: %i[show update]
  resources :line_items, only: %i[create update destroy]
  resources :orders, controller: 'orders/orders', only: %i[index show create] do
    resources :checkout, controller: 'orders/checkout', only: %i[index show update]
  end

  root 'home#index'
  get 'home/index'
  get 'settings/edit'
  put 'settings/update'
  patch 'settings/update_email'
  patch 'settings/change_password'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @latest_books = Book.order('created_at DESC').limit(3)
    @best_sellers = []
    @categories.each { |category| @best_sellers << Book.best_seller(category.name) }
  end
end

app/views/home/_best_sellers.html.haml
- @best_sellers.each do |bestseller|
  .col-sm-6.col-md-3
    .general-thumb-wrap
      .thumbnail.general-thumbnail
        = image_tag bestseller.images.first,
                    class: 'img-shadow general-thumbnail-img', alt: "design-book"
        .thumb-hover
          .general-thumb-link-wrap
            = link_to book_path(bestseller), id: "book-view-#{bestseller.id}",
                      class: 'thumb-hover-link' do
              %i.fa.fa-eye.thumb-icon{'aria-hidden': "true"}
            = link_to line_items_path(book_id: bestseller.id, quantity: 1),
                      id: "add-book-#{bestseller.id}-to-cart",
                      method: :post, class: 'thumb-hover-link' do
              %i.fa.fa-shopping-cart.thumb-icon
    .mb-35
      .clearfix
        %p.pull-right.font-16.in-gold-500= bestseller.decorate.price
        %p.title.mr-55= bestseller.title
      %span.divider-sm
      %p.lead.small= bestseller.decorate.authors_names

app/views/home/_latest_book.html.haml
.row
  .col-sm-5
    .general-img-wrap
      = image_tag latest_book.images.first,
                  class: 'img-shadow general-thumbnail-img', alt: "design-book"
  .col-sm-7
    .mb-60
      %h1= latest_book.title
      %p.lead= latest_book.decorate.short_description
      %p.lead.small= latest_book.decorate.authors_names
      .general-align
        = button_to t('.buy_now'),
                    line_items_path(book_id: latest_book.id, quantity: 1),
                    class: 'btn btn-primary'

app/views/home/index.html.haml
#slider.carousel.slide{'data-ride': "carousel"}
  %ol.carousel-indicators
    %li.active{'data-target': "#slider", 'data-slide-to': "0"}
    %li{'data-target': "#slider", 'data-slide-to': "1"}
    %li{'data-target': "#slider", 'data-slide-to': "2"}
  .carousel-inner{role: "listbox"}
    .item.active
      = render partial: 'latest_book', object: @latest_books.first
    - (1..@latest_books.count-1).each do |index|
      .item
        = render partial: 'latest_book', object: @latest_books[index]
  %a.left.carousel-control{href: "#slider", role: "button", 'data-slide': "prev"}
    %span.icon-prev{'aria-hidden': "true"}
    %span.sr-only= t '.previous'
  %a.right.carousel-control{href: "#slider", role: "button", 'data-slide': "next"}
    %span.icon-next{'aria-hidden': "true"}
    %span.sr-only= t '.next'
.container
.jumbotron.text-center.mb-0
  %h2.h1= t '.welcome'
  .mb-res-50
    %p= t '.about_us'
  = button_to t('.get_started'), books_path, method: :get, class: 'btn btn-default'
#bestsellers.mb-35
  %h3= t '.best_sellers'
  .row
    = render partial: 'best_sellers'