config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :books, only: %i[index show] do
    resources :reviews, only: :create
  end
  resources :carts, only: %i[show update]
  resources :line_items, only: %i[create update destroy]
  resources :orders, controller: 'orders/orders', only: %i[index show create] do
    resources :checkout, controller: 'orders/checkout', only: %i[index show update]
  end

  root 'home#index'
  get 'home/index'
  get 'settings/edit'
  put 'settings/update'
  patch 'settings/update_email'
  patch 'settings/change_password'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

app/models/line_item.rb
# frozen_string_literal: true

class LineItem < ApplicationRecord
  belongs_to :book
  belongs_to :cart, optional: true
  belongs_to :order, optional: true

  validates :quantity, presence: true,
                       numericality: { only_integer: true, greater_than_or_equal_to: 1 }

  def subtotal
    price * quantity
  end
end

app/controllers/line_items_controller.rb
# frozen_string_literal: true

class LineItemsController < ApplicationController
  load_and_authorize_resource only: %i[update destroy]
  authorize_resource only: :create

  def create
    book = Book.find(params[:book_id])
    @line_item = @cart.add_product(book, params[:quantity])
    if @line_item.save
      redirect_back fallback_location: root_path, notice: t('.success')
    else
      redirect_back fallback_location: root_path, alert: t('.fail')
    end
  rescue StandardError
    redirect_back fallback_location: root_path,
                  alert: t('.enter_positive_integer')
  end

  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.js
      else
        format.js { redirect_to @cart }
      end
    end
  end

  def destroy
    @line_item.destroy
    redirect_to @cart, notice: t('.success')
  end

  private

  def line_item_params
    params.require(:line_item).permit(:quantity)
  end
end

app/views/line_items/_form_hidden_xs.html.haml
%tr{id: "line-item-#{line_item.id}"}
  %td
    .general-img-wrap-table
      = link_to book_path(line_item.book), id: "photo-view-#{line_item.book.id}" do
        = image_tag line_item.book.images.first,
                    alt: "design-book", class: 'cart-img-shadow pull-left'
  %td
    = link_to book_path(line_item.book), class: 'mb-20', id: "title-view-#{line_item.book.id}" do
      %p.title.in-gold-500= line_item.book.title
  %td
    %span.font-16.in-gold-500= line_item.decorate.price
  %td
    .input-group
      = form_for line_item, id: "form-line-item-#{line_item.id}", remote: true do |f|
        = link_to '#', id: "minus-#{line_item.id}",
                       class: 'input-link quantity-input-minus' do
          %i.fa.fa-minus.line-height-40 &nbsp
        = f.text_field :quantity, id: "input-line-item-#{line_item.id}",
                        class: 'form-control quantity-input'
        = link_to '#', id: "plus-#{line_item.id}",
                       class: 'input-link quantity-input-plus' do
          %i.fa.fa-plus.line-height-40 &nbsp
        = f.submit '#', id: "update-line-item-#{line_item.id}", hidden: true

  %td
    %span.font-16.in-gold-500{id: "subtotal-#{line_item.id}"}
      = line_item.decorate.subtotal
  %td
    = button_to line_item_path(line_item), method: :delete, type: "button",
                id: "delete-#{line_item.id}",
                class: "close general-cart-close", 'aria-label': "Close" do
      %span{'aria-hidden': "true"} &times;

app/views/line_items/_form_visible_xs.html.haml
.general-cart-item.divider-lg-bottom{id: "line-item-#{line_item.id}-xs"}
  %button.close.general-cart-close{type: "button", 'aria-label': "Close"}
    %span{'aria-hidden': "true"} &times;
  .general-img-wrap-table
    = link_to book_path(line_item.book), id: "photo-view-#{line_item.book.id}-xs" do
      = image_tag line_item.book.images.first,
                  class: 'cart-img-shadow', alt: "design-book"
  = link_to book_path(line_item.book), id: "title-view-#{line_item.book.id}-xs" do
    %p.title.in-gold-500= line_item.book.title
  %table.table
    %tr
      %td
        %span.in-grey-600= t '.price'
      %td
        %span.font-16.in-gold-500= line_item.decorate.price
    %tr
      %td.vertical-middle
        %span.in-grey-600= t '.quantity'
      %td
        .input-group
          = form_for line_item, id: "form-line-item-#{line_item.id}-xs", remote: true do |f|
            = link_to '#', id: "minus-#{line_item.id}-xs",
                           class: 'input-link quantity-input-minus' do
              %i.fa.fa-minus.line-height-40 &nbsp
            = f.text_field :quantity, id: "input-line-item-#{line_item.id}-xs",
                            class: 'form-control quantity-input'
            = link_to '#', id: "plus-#{line_item.id}-xs",
                           class: 'input-link quantity-input-plus' do
              %i.fa.fa-plus.line-height-40 &nbsp
            = f.submit '#', id: "update-line-item-#{line_item.id}-xs", hidden: true
    %tr
      %td
        %span.in-grey-600= t '.sub_total'
      %td
        %span.font-16.in-gold-500= line_item.decorate.subtotal

app/views/line_items/_line_item.html.haml
%tr
  %td
    .general-img-wrap-table
      = image_tag line_item.book.image_url, alt: "design-book",
                  class: 'cart-img-shadow pull-left'
      -# %img.cart-img-shadow.pull-left{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
  %td
    %p.title= line_item.book.title
  %td
    %span.font-16.in-gold-500= number_to_currency(line_item.book.price)
  %td
    .input-group
      %a.input-link{href: "#"}
        %i.fa.fa-minus.line-heaght-40
      %input.form-control.quantity-input{type: "text", value: "#{line_item.quantity}"}
      %a.input-link{href: "#"}
        %i.fa.fa-plus.line-heaght-40
  %td
    %span.font-16.in-gold-500 €32.90 need to do
  %td
    %button.close.general-cart-close{type: "button", 'aria-label': "Close"}
      %span{'aria-hidden': "true"} &times;


-# %tr
-#   %td
-#     .general-img-wrap-table
-#       %img.cart-img-shadow.pull-left{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
-#   %td
-#     %p.title Android Programming for Beginners
-#   %td
-#     %span.font-16.in-gold-500 €28.50
-#   %td
-#     .input-group
-#       %a.input-link{href: "#"}
-#         %i.fa.fa-minus.line-heaght-40
-#       %input.form-control.quantity-input{type: "text"}
-#       %a.input-link{href: "#"}
-#         %i.fa.fa-plus.line-heaght-40
-#   %td
-#     %span.font-16.in-gold-500 €32.90
-#   %td
-#     %button.close.general-cart-close{type: "button", 'aria-label': "Close"}
-#       %span{'aria-hidden': "true"} &times;
-# %tr
-#   %td
-#     .general-img-wrap-table
-#       %img.cart-img-shadow.pull-left{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
-#   %td
-#     %p.title Android Programming for Beginners
-#   %td
-#     %span.font-16.in-gold-500 €28.50
-#   %td
-#     .input-group
-#       %a.input-link{href: "#"}
-#         %i.fa.fa-minus.line-heaght-40
-#       %input.form-control.quantity-input{type: "text"}
-#       %a.input-link{href: "#"}
-#         %i.fa.fa-plus.line-heaght-40
-#   %td
-#     %span.font-16.in-gold-500 €32.90
-#   %td
-#     %button.close.general-cart-close{type: "button", 'aria-label': "Close"}
-#       %span{'aria-hidden': "true"} &times;

app/views/line_items/_line_item_hidden_xs.html.haml
%tr{id: "line-item-#{line_item.id}"}
  %td
    .general-img-wrap-table
      = image_tag line_item.book.image_url, alt: "design-book",
                  class: 'cart-img-shadow pull-left'
      -# %img.cart-img-shadow.pull-left{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
  %td
    %p.title= line_item.book.title
  %td
    %span.font-16.in-gold-500= number_to_currency(line_item.book.price)
  %td
    .input-group

      = form_tag line_items_path(book_id: line_item.book.id), id: 'line-item-form' do
        = link_to '', class: 'input-link',
                  onclick: "decrementQuantity(); return false;" do
          %i.fa.fa-minus.line-height-40
        %input.form-control.quantity-input{name: 'quantity', type: "text", value: 1}
        -# = text_field_tag :quantity, class: 'form-control quantity-input', value: 1
        -# = submit_tag t('.add_to_cart'), class: 'btn btn-default pull-right general-position'
        = link_to '', class: 'input-link',
                  onclick: "incrementQuantity(); return false;" do
          %i.fa.fa-plus.line-height-40

      -# %a.input-link{href: "#"}
      -#   %i.fa.fa-minus.line-heaght-40
      -# %input.form-control.quantity-input{type: "text", value: "#{line_item.quantity}"}
      -# %a.input-link{href: "#"}
      -#   %i.fa.fa-plus.line-heaght-40

  %td
    %span.font-16.in-gold-500 €32.90 need to do smth.
  %td
    %button.close.general-cart-close{type: "button", 'aria-label': "Close"}
      %span{'aria-hidden': "true"} &times;


-# %tr
-#   %td
-#     .general-img-wrap-table
-#       %img.cart-img-shadow.pull-left{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
-#   %td
-#     %p.title Android Programming for Beginners
-#   %td
-#     %span.font-16.in-gold-500 €28.50
-#   %td
-#     .input-group
-#       %a.input-link{href: "#"}
-#         %i.fa.fa-minus.line-heaght-40
-#       %input.form-control.quantity-input{type: "text"}
-#       %a.input-link{href: "#"}
-#         %i.fa.fa-plus.line-heaght-40
-#   %td
-#     %span.font-16.in-gold-500 €32.90
-#   %td
-#     %button.close.general-cart-close{type: "button", 'aria-label': "Close"}
-#       %span{'aria-hidden': "true"} &times;
-# %tr
-#   %td
-#     .general-img-wrap-table
-#       %img.cart-img-shadow.pull-left{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
-#   %td
-#     %p.title Android Programming for Beginners
-#   %td
-#     %span.font-16.in-gold-500 €28.50
-#   %td
-#     .input-group
-#       %a.input-link{href: "#"}
-#         %i.fa.fa-minus.line-heaght-40
-#       %input.form-control.quantity-input{type: "text"}
-#       %a.input-link{href: "#"}
-#         %i.fa.fa-plus.line-heaght-40
-#   %td
-#     %span.font-16.in-gold-500 €32.90
-#   %td
-#     %button.close.general-cart-close{type: "button", 'aria-label': "Close"}
-#       %span{'aria-hidden': "true"} &times;

app/views/line_items/_line_item_visible_xs.html.haml
.general-cart-item.divider-lg-bottom
  %button.close.general-cart-close{type: "button", 'aria-label': "Close"}
    %span{'aria-hidden': "true"} &times;
  .general-img-wrap-table
    = image_tag line_item.book.image_url, class: 'cart-img-shadow', alt: "design-book"
  %p.title= line_item.book.title
  %table.table
    %tr
      %td
        %span.in-grey-600= t '.price'
      %td
        %span.font-16.in-gold-500= number_to_currency(line_item.book.price)
    %tr
      %td.vertical-middle
        %span.in-grey-600= t '.quantity'
      %td
        .input-group


          = form_tag line_items_path(book_id: line_item.book.id), id: 'line-item-form' do
            = link_to '', class: 'input-link',
                      onclick: "decrementQuantity(); return false;" do
              %i.fa.fa-minus.line-height-40
            %input.form-control.quantity-input{name: 'quantity', type: "text", value: 1}
            -# = text_field_tag :quantity, class: 'form-control quantity-input', value: 1
            -# = submit_tag t('.add_to_cart'), class: 'btn btn-default pull-right general-position'
            = link_to '', class: 'input-link',
                      onclick: "incrementQuantity(); return false;" do
              %i.fa.fa-plus.line-height-40


          -#
          -# %a.input-link{href: "#"}
          -#   %i.fa.fa-minus.line-heaght-40
          -# %input.form-control.quantity-input{type: "text"} 57
          -# %a.input-link{href: "#"}
          -#   %i.fa.fa-plus.line-heaght-40
    %tr
      %td
        %span.in-grey-600= t '.subtotal'
      %td
        %span.font-16.in-gold-500 €32.90 Need to do smth.



-# .general-cart-item.divider-lg-bottom
-#   %button.close.general-cart-close{type: "button", 'aria-label': "Close"}
-#     %span{'aria-hidden': "true"} &times;
-#   .general-img-wrap-table
-#     = image_tag "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg",
-#       class: 'cart-img-shadow', alt: "design-book"
-#     -# %img.cart-img-shadow{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
-#   %p.title Android Programming for Beginners
-#   %table.table
-#     %tr
-#       %td
-#         %span.in-grey-600= t '.price'
-#       %td
-#         %span.font-16.in-gold-500 €28.50
-#     %tr
-#       %td.vertical-middle
-#         %span.in-grey-600= t '.quantity'
-#       %td
-#         .input-group
-#           %a.input-link{href: "#"}
-#             %i.fa.fa-minus.line-heaght-40
-#           %input.form-control.quantity-input{type: "text"} 57
-#           %a.input-link{href: "#"}
-#             %i.fa.fa-plus.line-heaght-40
-#     %tr
-#       %td
-#         %span.in-grey-600= t '.subtotal'
-#       %td
-#         %span.font-16.in-gold-500 €32.90
-# .general-cart-item.divider-lg-bottom.mb-30
-#   %button.close.general-cart-close{type: "button", 'aria-label': "Close"}
-#     %span{'aria-hidden': "true"} &times;
-#   .general-img-wrap-table
-#     %img.cart-img-shadow{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
-#   %p.title Android Programming for Beginners
-#   %table.table
-#     %tr
-#       %td
-#         %span.in-grey-600 Price
-#       %td
-#         %span.font-16.in-gold-500 €28.50
-#     %tr
-#       %td.vertical-middle
-#         %span.in-grey-600 Quantity
-#       %td
-#         .input-group
-#           %a.input-link{href: "#"}
-#             %i.fa.fa-minus.line-heaght-40
-#           %input.form-control.quantity-input{type: "text"}
-#           %a.input-link{href: "#"}
-#             %i.fa.fa-plus.line-heaght-40
-#     %tr
-#       %td
-#         %span.in-grey-600 SubTotal
-#       %td
-#         %span.font-16.in-gold-500 €32.90

app/views/line_items/update.js.erb
var input = "#input-line-item-<%= params[:id] %>";
$(input).val(<%= @line_item.quantity %>);
$("#subtotal-<%= params[:id] %>").text("<%= @line_item.decorate.subtotal %>");
$("#cart-subtotal").text("<%= @line_item.cart.decorate.subtotal %>");
$("#coupon").text("<%= @line_item.cart.decorate.discount %>");
$("#cart-total").text("<%= @line_item.cart.decorate.total %>");
$("span#cart").html("<%= @line_item.cart.products_quantity %>");
$("span#cart-xs").html("<%= @line_item.cart.products_quantity %>");