config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :books, only: %i[index show] do
    resources :reviews, only: :create
  end
  resources :carts, only: %i[show update]
  resources :line_items, only: %i[create update destroy]
  resources :orders, controller: 'orders/orders', only: %i[index show create] do
    resources :checkout, controller: 'orders/checkout', only: %i[index show update]
  end

  root 'home#index'
  get 'home/index'
  get 'settings/edit'
  put 'settings/update'
  patch 'settings/update_email'
  patch 'settings/change_password'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

app/views/layouts/_account_menu.html.haml
- if user_signed_in?
  %li.dropdown
    %a.dropdown-toggle{href: "#", 'data-toggle': "dropdown",
      role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
      = t 'layouts.application.my_account'
    %ul.dropdown-menu
      %li= link_to t('layouts.application.orders'), orders_path
      %li= link_to t('layouts.application.settings'), settings_edit_path
      %li.divider{role: "separator"}
      %li= link_to t('layouts.application.logout'), destroy_user_session_path, method: :delete
- else
  %li= link_to t('devise.sessions.new.sign_in'), new_user_session_path
  %li= link_to t('devise.shared.links.sign_up'), new_user_registration_path

app/views/layouts/_footer.html.haml
%footer.navbar-inverse
  .container
    .row
      .col-sm-9
        %ul.list-inline.general-align.mb-25
          %li= link_to t('layouts.application.home'), root_path, class: 'nav-link'
          %li= link_to t('layouts.application.shop'), books_path, class: 'nav-link'
          - if user_signed_in?
            %li= link_to t('layouts.application.orders'), orders_path, class: 'nav-link'
            %li= link_to t('layouts.application.settings'), settings_edit_path, class: 'nav-link'
      .col-sm-3
        %p.general-nav-mail= t '.support'
        %p.general-nav-number= t '.phone_number'
        %ul.list-inline.general-align
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-facebook{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-twitter{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-google-plus{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-instagram{'aria-hidden': "true"}

app/views/layouts/_header.html.haml
%header.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.pull-left{type: "button", 'data-toggle': "collapse",
        'data-target': "#navbar"}
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand= t '.bookstore'
      = link_to @cart, class: 'shop-link pull-right visible-xs' do
        %span.shop-icon
          %span#cart-xs.shop-quantity= @cart.products_quantity
    = link_to @cart, class: 'shop-link pull-right hidden-xs', id: 'cart' do
      %span.shop-icon
        %span#cart.shop-quantity= @cart.products_quantity
    #navbar.navbar-collapse.collapse.pl-30{'aria-expanded': "false"}

      .visible-xs
        %button.close{type: "button", 'aria-label': "Close"}
          %span{'aria-hidden': "true"} &times;
        %ul.nav.navbar-nav
          %li
            = link_to t('layouts.application.home'), root_path
          %li
            %a{type: "button", 'data-toggle': "collapse", href: "#menu", 'aria-expanded': "false", 'aria-controls': "menu"}= t 'application.header.shop'
            %ul#menu.collapse.list-unstyled.pl-30.mb-10{'aria-expanded': "false"}
              - @categories.each do |category|
                %li= link_to t("books.categories.#{category.name.downcase.tr(' ', '_')}"),
                            books_path(category: category.name),
                            class: 'collapse-link'
          = render 'layouts/account_menu'

      .hidden-xs
        %ul.nav.navbar-nav
          %li= link_to t('layouts.application.home'), root_path
          %li.dropdown
            %a.dropdown-toggle{href: "#", 'data-toggle': "dropdown", role: "button",    'aria-haspopup': "true", 'aria-expanded': "false"}
              = t 'layouts.application.shop'
            %ul.dropdown-menu
              - @categories.each do |category|
                %li= link_to t("books.categories.#{category.name.downcase.tr(' ', '_')}"),
                              books_path(category: category.name)
          = render 'layouts/account_menu'

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %meta{charset: "UTF-8"}
    %meta{name: "viewport", content: "width=device-width"}
    %title= t 'layouts.header.bookstore'

    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render 'layouts/header'

    %main.container.general-main-wrap
      - if flash.any?
        %p#notice= notice
        %p#alert= alert

      = yield

    = render 'layouts/footer'